version: '3.8'

services:
  app:
    image: fajri:webserver
    ports:
      - "32769:22"
      - "80:80"
      - "443:443"
    environment:
      - TIMEZONE=Asia/Jakarta
      - SSH_SERVICE=start
      - SSH_USER=developer
      - SSH_PASSWORD=@Dev5kwn24
      - POST_MAX_SIZE=10M
      - MEMORY_LIMIT=256M
      - MAX_INPUT_VARS=1000
      - UPLOAD_MAX_FILESIZE=10M
      - MAX_EXECUTION_TIME=60
      - MAX_INPUT_TIME=120
    volumes:
      - apps-data:/var/www/html
      - nginx-conf:/etc/nginx
      - worker:/etc/supervisor/
    restart: always
    tty: true

volumes:
  apps-data:
  nginx-conf:
  worker: